[build]
  command = "npm run build"
  publish = "dist"

[[edge_functions]]
path = "/donate/success"
function = "success-headers"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 301
